version: 2
updates:
  # Gradleの依存関係更新
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    reviewers:
      - "char5742"
    labels:
      - "dependencies"
      - "gradle"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # メジャーバージョンアップは手動で行う
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Groovyのバージョンは慎重に管理
      - dependency-name: "org.apache.groovy:*"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
        
  # GitHub Actionsの更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    reviewers:
      - "char5742"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      
  # Dockerイメージの更新（将来的に追加される場合）
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build"