# .octocov.yml — Groovy LSP

# --------------------------------------------------
# 基本設定
# --------------------------------------------------
repository: ${GITHUB_REPOSITORY}   # 明示するとローカル実行でも安心
timeout:   2m                      # 大きめに確保（既定 30s）

# --------------------------------------------------
# Code Coverage
# --------------------------------------------------
coverage:
  # Jacoco ルートレポート
  paths:
    - build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml

  # 除外パターン
  exclude:
    - "**/test/**"
    - "**/tests/**"
    - "**/benchmarks/**"
    - "**/vscode-extension/**"
    - "**/*Test.java"
    - "**/*Spec.groovy"
    - "**/generated/**"
    - "**/Main.java"
    - "**/Launcher*"
    - "**/Module*"
    - "**/Constants*"

  # バッジ
  badge:
    path: docs/coverage.svg

  # 最低許容値（例：80% 未満なら CI 落とす）
  acceptable: 80%

# --------------------------------------------------
# Code ⇄ Test Ratio
# --------------------------------------------------
codeToTestRatio:
  code:
    - "packages/**/src/main/**/*.java"
    - "packages/**/src/main/**/*.groovy"
    - "!packages/integration-tests/**"
    - "!packages/benchmarks/**"
    - "!packages/vscode-extension/**"
  test:
    - "packages/**/src/test/**/*.java"
    - "packages/**/src/test/**/*.groovy"
    - "packages/integration-tests/**/*.java"
    - "packages/integration-tests/**/*.groovy"
  badge:
    path: docs/ratio.svg
  # acceptable: 1:1.2          # 必要なら解放

# --------------------------------------------------
# Test Execution Time
# --------------------------------------------------
testExecutionTime: {}             # GA 上では自動計測される

# --------------------------------------------------
# Pull Request Comment
# --------------------------------------------------
comment:
  if: is_pull_request
  deletePrevious: true
  hideFooterLink: false
  # message: "👀 テスト通りました！"  # 追記メッセージ例

# --------------------------------------------------
# 過去レポート保存 & 差分比較
# --------------------------------------------------
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}

# --------------------------------------------------
# Job Summary 出力
# --------------------------------------------------
summary: {}

# --------------------------------------------------
# バッジ自動 push（デフォルトブランチのみ）
# --------------------------------------------------
push:
  if: is_default_branch
  # message: "Update badges by octocov [skip ci]"
