name: CI

on:
  push:
    branches: [ main, develop, 'feature/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test (${{ matrix.runtime }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [node22, java21]
    
    steps:
    - uses: actions/checkout@v4
    
    # Setup for Java tests
    - name: Set up JDK 21
      if: matrix.runtime == 'java21'
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
        cache: gradle
    
    - name: Build and Test Java
      if: matrix.runtime == 'java21'
      run: ./gradlew build test --no-daemon
    
    # Setup for Node tests
    - name: Set up Node.js 22
      if: matrix.runtime == 'node22'
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    
    - name: Install pnpm
      if: matrix.runtime == 'node22'
      uses: pnpm/action-setup@v3
      with:
        version: 9
    
    - name: Install dependencies
      if: matrix.runtime == 'node22'
      run: pnpm install
    
    - name: Build Java artifacts for Node tests
      if: matrix.runtime == 'node22'
      run: ./gradlew :server-launcher:shadowJar
    
    - name: Run Protocol Tests
      if: matrix.runtime == 'node22'
      run: pnpm run test:protocol
    
    # E2E tests with xvfb for VS Code
    - name: Run E2E Tests
      if: matrix.runtime == 'node22'
      uses: coactions/setup-xvfb@v1
      with:
        run: pnpm run test:e2e