name: VSCode Extension E2E Tests

on:
  push:
    paths:
      - 'packages/vscode-extension/**'
      - 'packages/server-launcher/**'
      - 'packages/lsp-protocol/**'
      - 'packages/groovy-core/**'
      - 'packages/workspace-index/**'
      - 'packages/codenarc-lint/**'
      - 'packages/formatting/**'
      - '.github/workflows/vscode-e2e.yml'
  pull_request:
    paths:
      - 'packages/vscode-extension/**'
      - 'packages/server-launcher/**'
      - 'packages/lsp-protocol/**'
      - 'packages/groovy-core/**'
      - 'packages/workspace-index/**'
      - 'packages/codenarc-lint/**'
      - 'packages/formatting/**'
      - '.github/workflows/vscode-e2e.yml'

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  e2e-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        vscode-version: ['stable', 'insiders']
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/vscode-extension/package-lock.json

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build language server
        run: ./gradlew :server-launcher:shadowJar --no-daemon

      - name: Copy language server JAR to extension
        run: |
          mkdir -p packages/vscode-extension/server
          cp packages/server-launcher/build/libs/*-all.jar packages/vscode-extension/server/groovy-language-server.jar
        shell: bash

      - name: Install extension dependencies
        working-directory: packages/vscode-extension
        run: npm ci

      - name: Compile extension
        working-directory: packages/vscode-extension
        run: npm run compile

      - name: Run E2E tests (Linux)
        if: runner.os == 'Linux'
        working-directory: packages/vscode-extension
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          npm run test:e2e
        env:
          VSCODE_VERSION: ${{ matrix.vscode-version }}

      - name: Run E2E tests (Windows/macOS)
        if: runner.os != 'Linux'
        working-directory: packages/vscode-extension
        run: npm run test:e2e
        env:
          VSCODE_VERSION: ${{ matrix.vscode-version }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results-${{ matrix.os }}-${{ matrix.vscode-version }}
          path: packages/vscode-extension/test-results/
          if-no-files-found: warn

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-screenshots-${{ matrix.os }}-${{ matrix.vscode-version }}
          path: packages/vscode-extension/screenshots/
          if-no-files-found: warn

  # Performance test job (runs on ubuntu-latest only)
  performance-test:
    runs-on: ubuntu-latest
    needs: e2e-test

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/vscode-extension/package-lock.json

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build language server
        run: ./gradlew :server-launcher:shadowJar --no-daemon

      - name: Copy language server JAR to extension
        run: |
          mkdir -p packages/vscode-extension/server
          cp packages/server-launcher/build/libs/*-all.jar packages/vscode-extension/server/groovy-language-server.jar

      - name: Install extension dependencies
        working-directory: packages/vscode-extension
        run: npm ci

      - name: Compile extension
        working-directory: packages/vscode-extension
        run: npm run compile

      - name: Run performance tests
        working-directory: packages/vscode-extension
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          npm run test:performance
        env:
          VSCODE_VERSION: stable

      - name: Upload performance results
        uses: actions/upload-artifact@v4
        with:
          name: performance-results
          path: packages/vscode-extension/performance-results/
          if-no-files-found: warn

  # Summary job
  e2e-check:
    needs: [e2e-test, performance-test]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Check E2E test results
        run: |
          if [[ "${{ needs.e2e-test.result }}" != "success" ]]; then
            echo "E2E tests failed"
            exit 1
          fi
          if [[ "${{ needs.performance-test.result }}" != "success" ]]; then
            echo "Performance tests failed"
            exit 1
          fi
          echo "All E2E tests completed successfully"
