name: VSCode Extension E2E Tests

on:
  workflow_dispatch:
    inputs:
      vscode-version:
        description: 'VS Code Version'
        required: true
        default: 'stable'
        type: choice
        options:
          - stable
          - insiders
          - both

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  e2e-test:
    strategy:
      matrix:
        vscode-version: ${{ fromJson(github.event.inputs.vscode-version == 'both' && '["stable", "insiders"]' || format('["{0}"]', github.event.inputs.vscode-version)) }}
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/vscode-extension/package-lock.json

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build language server
        run: ./gradlew :server-launcher:shadowJar --no-daemon

      - name: Copy language server JAR to extension
        run: |
          mkdir -p packages/vscode-extension/server
          cp packages/server-launcher/build/libs/groovy-language-server-*.jar packages/vscode-extension/server/groovy-language-server.jar
        shell: bash

      - name: Install extension dependencies
        working-directory: packages/vscode-extension
        run: npm ci

      - name: Compile extension
        working-directory: packages/vscode-extension
        run: npm run compile

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk-bridge2.0-0 \
            libdrm2 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libgbm1 \
            libxkbcommon0 \
            libasound2t64 \
            xvfb

      - name: Install E2E test dependencies
        working-directory: packages/e2e-tests/vscode-test
        run: npm ci

      - name: Run E2E tests
        working-directory: packages/e2e-tests/vscode-test
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          npm test
        env:
          VSCODE_VERSION: ${{ matrix.vscode-version }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results-${{ matrix.vscode-version }}
          path: |
            packages/e2e-tests/vscode-test/test-results/
            packages/e2e-tests/vscode-test/.vscode-test/logs/
          if-no-files-found: warn

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-screenshots-${{ matrix.vscode-version }}
          path: |
            packages/e2e-tests/vscode-test/screenshots/
            packages/e2e-tests/vscode-test/.vscode-test/screenshots/
          if-no-files-found: warn


  # Summary job
  e2e-check:
    needs: [e2e-test]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Check E2E test results
        run: |
          if [[ "${{ needs.e2e-test.result }}" != "success" ]]; then
            echo "E2E tests failed"
            exit 1
          fi
          echo "All E2E tests completed successfully"
